### PR TITLE
Update Cargo.toml

### PR DESCRIPTION
**Pull request by Dylan-DPC**
Updates dependency to the patch version of 0.9.8

[Advisory](https://rustsec.org/advisories/RUSTSEC-2023-0031.html)

### CODE REVIEW

**Comment by Restioson** [comment]
Hi Dylan, thanks for opening this! I think catty shouldn't be affected by
the vulnerability, luckily, since it is only using the Mutex from spin. I
will merge this when I am home from holiday as I have limited reception
here.

**Comment by Dylan-DPC** [comment]
Yes sure, but this ts to ensure it eliminates the possibility of unpatched versions from showing up in the dependency tree whether for your project or any other (ofc it requires people setting up upper bounds at the patch version or pinning or going for lowest versions but still :P )

Yeah take your time no worries :)

**Comment by Restioson** [comment]
Yea of course, I'll merge when back ASAP, just very difficult to do
anything else except email from here

**Comment by Restioson** [comment]
Apologies for fogetting about this :sweat_smile:

**Pull request merged**
